version: '3.8'

services:
  weatherlink:
    build: .
    ports:
      - "8080:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]